---

# Setup LVM partition

- name: storage | create logical volume
  become: yes
  lvol:
    vg: "{{ lvm_vgname }}"
    lv: "{{ lvm_lvname }}"
    size: "{{ lvm_lvsize }}"
    shrink: "{{ lvm_shrink }}"
    opts: "{{ lvm_lvopts }}"

- name: storage | format
  become: yes
  filesystem:
    fstype: "{{ lvm_lvfilesystem }}"
    dev: /dev/{{ lvm_vgname }}/{{ lvm_lvname }}
    resizefs: yes

- name: storage | mount
  become: yes
  mount:
    name: "{{ lvm_lvmount }}"
    src: /dev/{{ lvm_vgname }}/{{ lvm_lvname }}
    dump: "{{ lvm_lvmount_dump }}"
    passno: "{{ lvm_lvmount_passno }}"
    fstype: "{{ lvm_lvfilesystem }}"
    state: mounted
